=== dbt-labs/dbt-core/schemas/dbt/run-results/v6.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "RunResultsArtifact",
  "properties": {
    "metadata": {
      "type": "object",
      "title": "BaseArtifactMetadata",
      "properties": {
        "dbt_schema_version": {
          "type": "string"
        },
        "dbt_version": {
          "type": "string",
          "default": "1.12.0a1"
        },
        "generated_at": {
          "type": "string"
        },
        "invocation_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "invocation_started_at": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "env": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "propertyNames": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "dbt_schema_version"
      ]
    },
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "RunResultOutput",
        "properties": {
          "status": {
            "anyOf": [
              {
                "enum": [
                  "success",
                  "error",
                  "skipped",
                  "partial success",
                  "no-op"
                ]
              },
              {
                "enum": [
                  "pass",
                  "error",
                  "fail",
                  "warn",
                  "skipped"
                ]
              },
              {
                "enum": [
                  "pass",
                  "warn",
                  "error",
                  "runtime error"
                ]
              }
            ]
          },
          "timing": {
            "type": "array",
            "items": {
              "type": "object",
              "title": "TimingInfo",
              "properties": {
                "name": {
                  "type": "string"
                },
                "started_at": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                },
                "completed_at": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                }
              },
              "additionalProperties": false,
              "required": [
                "name"
              ]
            }
          },
          "thread_id": {
            "type": "string"
          },
          "execution_time": {
            "type": "number"
          },
          "adapter_response": {
            "type": "object",
            "propertyNames": {
              "type": "string"
            }
          },
          "message": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "failures": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ]
          },
          "unique_id": {
            "type": "string"
          },
          "compiled": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ]
          },
          "compiled_code": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "relation_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "batch_results": {
            "anyOf": [
              {
                "type": "object",
                "title": "BatchResults",
                "properties": {
                  "successful": {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "prefixItems": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "string"
                        }
                      ],
                      "maxItems": 2,
                      "minItems": 2
                    }
                  },
                  "failed": {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "prefixItems": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "string"
                        }
                      ],
                      "maxItems": 2,
                      "minItems": 2
                    }
                  }
                },
                "additionalProperties": false
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "additionalProperties": false,
        "required": [
          "status",
          "timing",
          "thread_id",
          "execution_time",
          "adapter_response",
          "message",
          "failures",
          "unique_id",
          "compiled",
          "compiled_code",
          "relation_name"
        ]
      }
    },
    "elapsed_time": {
      "type": "number"
    },
    "args": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "metadata",
    "results",
    "elapsed_time"
  ],
  "$id": "https://schemas.getdbt.com/dbt/run-results/v6.json"
}

=== dbt-labs/dbt-core/tests/functional/artifacts/data/results/v6/run_results.json
{"metadata": {"dbt_schema_version": "https://schemas.getdbt.com/dbt/run-results/v6.json", "dbt_version": "1.9.0a1", "generated_at": "2024-09-24T15:24:36.246406Z", "invocation_id": "ca07d2ca-054f-4ea1-be63-4acccfe4a6a7", "env": {}}, "results": [{"status": "success", "timing": [{"name": "compile", "started_at": "2024-09-24T15:24:36.181448Z", "completed_at": "2024-09-24T15:24:36.183192Z"}, {"name": "execute", "started_at": "2024-09-24T15:24:36.185536Z", "completed_at": "2024-09-24T15:24:36.231442Z"}], "thread_id": "Thread-9 (worker)", "execution_time": 0.0535128116607666, "adapter_response": {"_message": "CREATE VIEW", "code": "CREATE VIEW", "rows_affected": -1}, "message": "CREATE VIEW", "failures": null, "unique_id": "model.test.my_model", "compiled": true, "compiled_code": "select 1 as id", "relation_name": "\"dbt\".\"test17271914717676665882_test_previous_version_state\".\"my_model\"", "batch_results": null}, {"status": "success", "timing": [{"name": "compile", "started_at": "2024-09-24T15:24:36.179261Z", "completed_at": "2024-09-24T15:24:36.182955Z"}, {"name": "execute", "started_at": "2024-09-24T15:24:36.183455Z", "completed_at": "2024-09-24T15:24:36.232800Z"}], "thread_id": "Thread-8 (worker)", "execution_time": 0.055058956146240234, "adapter_response": {"_message": "CREATE VIEW", "code": "CREATE VIEW", "rows_affected": -1}, "message": "CREATE VIEW", "failures": null, "unique_id": "model.test.metricflow_time_spine", "compiled": true, "compiled_code": "SELECT to_date('02/20/2023', 'mm/dd/yyyy') as date_day", "relation_name": "\"dbt\".\"test17271914717676665882_test_previous_version_state\".\"metricflow_time_spine\"", "batch_results": null}], "elapsed_time": 0.6437027454376221, "args": {"profiles_dir": "/private/var/folders/79/5290gpvn3lx5jdryk4844rm80000gn/T/pytest-of-quigleymalcolm/pytest-139/profile0", "invocation_command": "dbt tests/functional/artifacts/test_previous_version_state.py", "strict_mode": false, "partial_parse_file_diff": true, "favor_state": false, "select": [], "log_level_file": "debug", "log_format_file": "debug", "which": "run", "introspect": true, "cache_selected_only": false, "log_level": "info", "defer": false, "static_parser": true, "macro_debugging": false, "write_json": true, "partial_parse": true, "version_check": true, "exclude": [], "use_colors_file": true, "indirect_selection": "eager", "project_dir": "/private/var/folders/79/5290gpvn3lx5jdryk4844rm80000gn/T/pytest-of-quigleymalcolm/pytest-139/project0", "require_resource_names_without_spaces": false, "warn_error_options": {"include": [], "exclude": []}, "log_path": "/Users/quigleymalcolm/Developer/dbt-labs/dbt-core/logs/test17271914717676665882", "printer_width": 80, "use_colors": true, "require_explicit_package_overrides_for_builtin_materializations": true, "show_resource_report": false, "quiet": false, "log_format": "default", "populate_cache": true, "send_anonymous_usage_stats": false, "source_freshness_run_project_hooks": false, "log_file_max_bytes": 10485760, "print": true, "vars": {}, "empty": false}}
